### ISSUE TITLE
MVP Roadmap for EigenLayer AVS and zkSNARK

### ISSUE THREAD

**Issue by v9n** [AvaProtocol/EigenLayer-AVS#1]
Delivery goal:

During this phase, we aim for a basic structure where we can have a RPC Oak AVS Operator node that can accept a RPC call to schedule the task.

For this time being the task will just be a simple task type to emit a message for now. Once we have implement the ERC6900 wallet we will start to integrate more task type.

The purpose of this is to simulate:

- End user can submit task to operator
- Task is eventually batched, a zkSNARK proof is generated with Groth16 to prove that we indeed store those task
- Node will check and execute the task. For now, just a single task type that is to emit an event on EVM

## Node implementation

- [ ] Base operator codebase that can compile and accept RPC call.
   -  [x] Task submission
   -  [ ] Task condition checking
- [x] Basic OAK aggrator
   -  [ ] zk proof task batch writen to L1
- [x] Can register this AVS on local testnet or on holesky testnet
- [ ] Anvil chain with pre-deploy contract to aid development
- [ ] zkSNARK implementation
- [x] AVS Operator setup script
    -  [x] Opt in
    -  [x] Opt out
    -  [x] Auto eject
-  [x] Testnet deployment on holesky with EigenLayer

## Contracts

- [ ] Oak TaskRegistry with EigenLayer
- [ ] ERC6900 wallet contracts
